server:
  port: 18089
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-jqb0laoy.cd.tencentcdb.com:10017/changgou_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: lean
    password: 12345ok!@#$%
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰功能