server:
  port: 18084
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: content
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-jqb0laoy.cd.tencentcdb.com:10017/changgou_content?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: lean
    password: 12345ok!@#$%
  redis:
    host: 139.199.117.109
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰功能

#hystrix 配置
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          #如果enabled设置为false，则请求超时交给ribbon控制
#          enabled: true
#        isolation:
#          strategy: SEMAPHORE
