server:
  port: 18093
spring:
  application:
    name: seckill
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-jqb0laoy.cd.tencentcdb.com:10017/changgou_seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: lean
    password: 12345ok!@#$%
  rabbitmq:
    addresses: 139.199.117.109
    connection-timeout: 15000
    username: jtest
    password: 123456
    port: 5672
    publisher-confirms: true
    virtual-host: test
  redis:
    host: 139.199.117.109
    port: 6379
    password: 12345ok12345
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000
          strategy: SEMAPHORE
logging:
  level:
    com:
      changgou:
        seckill:
          dao: Info