server:
  port: 9001
spring:
  application:
    name: user-auth
  redis:
    host: 139.199.117.109
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-jqb0laoy.cd.tencentcdb.com:10017/changgou_oauth?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: lean
    password: 12345ok!@#$%
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: changgou
  clientSecret: changgou
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/changgou.jks
    secret: changgou
    alias: changgou
    password: changgou