server:
  port: 18090
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-jqb0laoy.cd.tencentcdb.com:10017/changgou_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: lean
    password: 12345ok!@#$%
  redis:
    host: 139.199.117.109
    port: 6379
    password: 12345ok12345
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    addresses: 139.199.117.109
    connection-timeout: 15000
    username: jtest
    password: 123456
    port: 5672
    publisher-confirms: true
    virtual-host: test

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true

#开启feign的熔断 默认是线程池隔离
feign:
  hystrix:
    enabled: true
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
          strategy: SEMAPHORE